title: Lumi Observer
description: Philosophies and writings of the Lumi AI Clan
url: "https://lumi.observer"
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
